// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebForm2021.Models;

namespace WebForm2021.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20210907093114_SeededDataUpdated")]
    partial class SeededDataUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebForm2021.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Email = "maryamyasser99@gmail.com",
                            Name = "Maryam Yasser"
                        },
                        new
                        {
                            ID = -2,
                            Email = "Habibayasser99@gmail.com",
                            Name = "Habiba Yasser"
                        });
                });

            modelBuilder.Entity("WebForm2021.Models.EmployeeSkill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SkillID");

                    b.ToTable("EmployeeSkills");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            EmployeeID = -1,
                            SkillID = -1
                        },
                        new
                        {
                            ID = -2,
                            EmployeeID = -1,
                            SkillID = -2
                        },
                        new
                        {
                            ID = -3,
                            EmployeeID = -2,
                            SkillID = -2
                        },
                        new
                        {
                            ID = -4,
                            EmployeeID = -2,
                            SkillID = -3
                        },
                        new
                        {
                            ID = -5,
                            EmployeeID = -2,
                            SkillID = -4
                        });
                });

            modelBuilder.Entity("WebForm2021.Models.Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "PHP"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Android"
                        },
                        new
                        {
                            ID = -3,
                            Name = "iOS"
                        },
                        new
                        {
                            ID = -4,
                            Name = "ASP.NET"
                        });
                });

            modelBuilder.Entity("WebForm2021.Models.EmployeeSkill", b =>
                {
                    b.HasOne("WebForm2021.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebForm2021.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebForm2021.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("WebForm2021.Models.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
